# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterStats' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for TwitterStats
	pod "PromiseKit", "~> 4.0"
	pod ‘STTwitter’
	pod ‘FLKAutoLayout’
	pod ’NSString+Emoji’
  target 'TwitterStatsTests' do
    inherit! :search_paths
    # Pods for testing
	pod "PromiseKit", "~> 4.0"
  end

end
